{{- if and .Values.auth.enabled (not .Values.auth.htpasswd.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pypiserver.fullname" . }}-auth
  labels:
    {{- include "pypiserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
{{ .Values.auth.htpasswd.content | indent 4 }}
{{- end }}
